// <auto-generated />
using System;
using LeaveRequestService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeaveRequestService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251007101933_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeaveRequestService.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateStart")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("LeaveTypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequestStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("RequestStatusId");

                    b.ToTable("LeaveRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 7, 12, 19, 32, 787, DateTimeKind.Local).AddTicks(4202),
                            DateEnd = new DateOnly(2025, 10, 15),
                            DateStart = new DateOnly(2025, 10, 10),
                            EmployeeId = 1,
                            LeaveTypeId = 1,
                            Reason = "Family vacation",
                            RequestStatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            ApprovedAt = new DateTime(2025, 10, 7, 12, 19, 32, 787, DateTimeKind.Local).AddTicks(4205),
                            CreatedAt = new DateTime(2025, 10, 7, 12, 19, 32, 787, DateTimeKind.Local).AddTicks(4204),
                            DateEnd = new DateOnly(2025, 9, 28),
                            DateStart = new DateOnly(2025, 9, 25),
                            EmployeeId = 2,
                            LeaveTypeId = 2,
                            Reason = "Flu recovery",
                            RequestStatusId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 7, 12, 19, 32, 787, DateTimeKind.Local).AddTicks(4207),
                            DateEnd = new DateOnly(2025, 10, 21),
                            DateStart = new DateOnly(2025, 10, 20),
                            EmployeeId = 3,
                            LeaveTypeId = 5,
                            Reason = "Personal reason",
                            RequestStatusId = 3
                        });
                });

            modelBuilder.Entity("LeaveRequestService.Models.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 7, 12, 19, 32, 787, DateTimeKind.Local).AddTicks(4080),
                            Description = "Paid time off for vacation or rest",
                            Name = "Annual Leave"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 7, 12, 19, 32, 787, DateTimeKind.Local).AddTicks(4092),
                            Description = "Leave for illness or medical appointments",
                            Name = "Sick Leave"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 7, 12, 19, 32, 787, DateTimeKind.Local).AddTicks(4093),
                            Description = "Short-term leave for personal reasons",
                            Name = "Casual Leave"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 7, 12, 19, 32, 787, DateTimeKind.Local).AddTicks(4094),
                            Description = "Leave for maternity-related reasons",
                            Name = "Maternity Leave"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 7, 12, 19, 32, 787, DateTimeKind.Local).AddTicks(4095),
                            Description = "Leave without pay",
                            Name = "Unpaid Leave"
                        });
                });

            modelBuilder.Entity("LeaveRequestService.Models.RequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 7, 12, 19, 32, 787, DateTimeKind.Local).AddTicks(4177),
                            Description = "Awaiting review or approval",
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 7, 12, 19, 32, 787, DateTimeKind.Local).AddTicks(4179),
                            Description = "Request has been approved",
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 7, 12, 19, 32, 787, DateTimeKind.Local).AddTicks(4180),
                            Description = "Request has been rejected",
                            Name = "Rejected"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 7, 12, 19, 32, 787, DateTimeKind.Local).AddTicks(4181),
                            Description = "Request was cancelled by employee",
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("LeaveRequestService.Models.LeaveRequest", b =>
                {
                    b.HasOne("LeaveRequestService.Models.LeaveType", "LeaveType")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeaveRequestService.Models.RequestStatus", "RequestStatus")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("RequestStatusId");

                    b.Navigation("LeaveType");

                    b.Navigation("RequestStatus");
                });

            modelBuilder.Entity("LeaveRequestService.Models.LeaveType", b =>
                {
                    b.Navigation("LeaveRequests");
                });

            modelBuilder.Entity("LeaveRequestService.Models.RequestStatus", b =>
                {
                    b.Navigation("LeaveRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
