// <auto-generated />
using System;
using EmployeesService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeesService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeesService.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 5, 12, 35, 37, 104, DateTimeKind.Local).AddTicks(9341),
                            Description = "Handles employee management, payroll, and company culture.",
                            IsActive = true,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 5, 12, 35, 37, 104, DateTimeKind.Local).AddTicks(9361),
                            Description = "Manages infrastructure, applications, and software development.",
                            IsActive = true,
                            Name = "IT Department"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 5, 12, 35, 37, 104, DateTimeKind.Local).AddTicks(9362),
                            Description = "Responsible for budgeting, financial planning, and reporting.",
                            IsActive = true,
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("EmployeesService.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            City = "Cairo",
                            Country = "Egypt",
                            CreatedAt = new DateTime(2025, 10, 5, 12, 35, 37, 104, DateTimeKind.Local).AddTicks(9505),
                            DateOfBirth = new DateOnly(1990, 5, 20),
                            DepartmentId = 2,
                            Email = "john.doe@company.com",
                            FirstName = "John",
                            Gender = "Male",
                            HireDate = new DateOnly(2020, 1, 15),
                            LastName = "Doe",
                            PhoneNumber = "01000000000",
                            PositionId = 1,
                            Salary = 8000m
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Nile St",
                            City = "Alexandria",
                            Country = "Egypt",
                            CreatedAt = new DateTime(2025, 10, 5, 12, 35, 37, 104, DateTimeKind.Local).AddTicks(9543),
                            DateOfBirth = new DateOnly(1994, 7, 10),
                            DepartmentId = 1,
                            Email = "sara.ahmed@company.com",
                            FirstName = "Sara",
                            Gender = "Female",
                            HireDate = new DateOnly(2021, 6, 1),
                            LastName = "Ahmed",
                            ManagerId = 1,
                            PhoneNumber = "01011111111",
                            PositionId = 2,
                            Salary = 7500m
                        });
                });

            modelBuilder.Entity("EmployeesService.Models.Employee", b =>
                {
                    b.HasOne("EmployeesService.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeesService.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("EmployeesService.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
